version: '3.7'

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "9090:9090"  # NiFi UI
      - "8081:8081"  # NiFi HTTP request port for data ingestion
    environment:
      NIFI_WEB_HTTP_PORT: 9090
    networks:
      - data-network
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO UI for S3-compatible API
      - "9001:9001"  # MinIO Console UI
    environment:
      MINIO_ROOT_USER: ...
      MINIO_ROOT_PASSWORD: ...
    command: server /data --console-address ":9001"
    networks:
      - data-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ...
      POSTGRES_PASSWORD: ...
      POSTGRES_DB: metabase_db
    ports:
      - "5432:5432"  # PostgreSQL port
    networks:
      - data-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "8085:80"  # pgAdmin UI
    environment:
      PGADMIN_DEFAULT_EMAIL: ...
      PGADMIN_DEFAULT_PASSWORD: ...
    networks:
      - data-network

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"  # Metabase UI
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: ...
      MB_DB_PASS: ...
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    networks:
      - data-network

networks:
  data-network:
    driver: bridge